name: Build Electron App

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --include=dev

      - name: Check vite exists
        run: npx vite --version

      - name: Build Vite
        run: npx vite build

      - name: Package Electron
        run: npx electron-builder

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: discord-bot-studio
          path: dist/
